<?php

namespace AppBundle\Repository;

/**
 * ContenuStaticEmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuStaticEmplacementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnassignedEmplacement(){

        return $this->createQueryBuilder('e')->leftJoin('e.contenuStatic', 'c')->where('c.emplacement IS NULL');

    }
}
