<?php

namespace AppBundle\Repository;

/**
 * ContenuStaticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuStaticRepository extends \Doctrine\ORM\EntityRepository
{

}
