<?php

namespace AppBundle\Repository;

/**
 * EvenementHistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementHistoriqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('ordre' => 'ASC'));
    }
}
