<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    function findByEvenement($evenement){

        $query = $this->createQueryBuilder('u')
            ->select('u')
            ->leftJoin('u.evenements', 'e')
            ->addSelect('e');

        $query = $query->add('where', $query->expr()->in('e', ':e'))
            ->setParameter('e', $evenement)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
