parameters:
    contactform.sender: '%mailer_user%'
    contactform.contacts:
        lutte: alfalutte@gmail.com
        grappling-fight: alfalutte@gmail.com
        musculation: alfalutte@gmail.com
        fitness: alfalutte@gmail.com
        administratif: clubalfa44@online.fr
    contactform.form:
        lutte: lutte
        grappling-fight: grappling-fight
        musculation: musculation
        fitness: fitness
        administratif: administratif
