app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
    methods:  [GET, POST, PUT, DELETE]
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
