# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    access_control:
        - { path: ^/efconnect, role: ROLE_ADMIN }
        - { path: ^/elfinder, role: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        mysql:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        main:
            pattern:    ^/
            anonymous: true
            http_basic: ~
            provider: mysql
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

