easy_admin:
    entities:
        Activite:
            class: AppBundle\Entity\Activite
            list:
                title: 'Activites du club'
                fields:
                    - 'nom'
                    - 'prix'
                    - 'isActive'
                    - { property: 'image', type: 'image', base_path: '%app.path.activite_images%' }
            form:
                title: "Ajout/Modification d'une activité"
                fields:
                    - 'nom'
                    - 'prix'
                    - 'placesDisponibles'
                    - { property: 'imageFile', type: 'vich_image' }
