easy_admin:
    entities:
        Actualite:
            class: AppBundle\Entity\Actualite
            list:
               title: 'liste des actualités'
               fields:
                   - date
                   - titre
                   - author
                   - { property: 'image', type: 'image', base_path: '%app.path.actualite_images%' }
            form:
                fields:
                - titre
                - { property: 'contenu', type: 'ckeditor' }
                - { property: 'imageFile', type: 'vich_image' }
            new:
                title: 'Nouvelle Actualité'
            edit:
                title: 'Modifier une Actualité'
            show:
                title: 'Actualité'
                actions:
                    - { name: 'sendActualiteNotification', icon: 'bell', label: 'Envoyer Notification', css_class: 'btn btn-info'}
                fields:
                    - date
                    - titre
                    - author
                    - contenu
                    - { property: 'image', type: 'image', base_path: '%app.path.actualite_images%' }
