easy_admin:
    entities:
        CategorieAge:
            class: AppBundle\Entity\CategorieAge
            list:
                title: "categories"
                fields:
                    - nom
                    - ageMin
                    - ageMax
                    - description
                    - prixBase

