easy_admin:
    entities:
        Competition:
            class: AppBundle\Entity\Competition
            list:
                title: 'Liste des competitions'
                fields:
                    - { property: 'image', type: 'image', label: 'Photo principale', base_path: '%app.path.competition_images%' }
                    - date
                    - titre
                    - description
                    - inscrits
                    - photos
            show:
                title: "Détail de l'évènement"
                actions:
                    - { name: 'exportInscriptions', icon: 'download', label: 'Export Excel', css_class: 'btn btn-info'}
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.competition_images%' }
                    - date
                    - titre
                    - description
                    - inscrits
                    - { property: 'photos' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - date
                    - titre
                    - description
                    - categorieAges
                    - activite
                    - { property: 'photos', type: 'collection', type_options: { entry_type: 'AppBundle\Form\PhotoType', by_reference: false }}
