easy_admin:
    entities:
        ContenuStaticEmplacement:
            class: AppBundle\Entity\ContenuStaticEmplacement
            list:
                title: 'Liste des emplacements'
                fields:
                    - 'name'
                    - 'url'
                    - { property: 'priority', label: 'priorité', type: 'decimal', format: '%01.1f'}
                    - 'contenuStatic'
            form:
                fields:
                    - 'name'
                    - 'url'
                    - 'priority'
