easy_admin:
    entities:
        ContenuStatic:
            class: AppBundle\Entity\ContenuStatic
            list:
                title: 'Liste des contenus statiques'
                fields:
                    - 'titre'
                    - 'description'
            form:
                fields:
                    - 'emplacement'
                    - 'titre'
                    - 'description'
                    - { property: 'contenu', type: 'ckeditor' }
