easy_admin:
    design:
        brand_color: '#000000'
        color_scheme: 'light'
        menu:
            - { entity: 'Actualite', label: 'Actualités' }
            - { entity: 'Photo', label: 'Photos' }
            - { entity: 'Evenement', label: 'Evenements'}
            - { entity: 'Competition', label: 'Competitions'}
            - { entity: 'User', label: 'Utilisateurs' }
            - { entity: 'ContenuStatic', label: 'Contenus Statiques'}
            - { entity: 'Activite', label: 'Activites'}
            - { entity: 'Categorie', label: 'Categories'}
            - { entity: 'ContenuStaticEmplacement', label: 'Emplacements'}
        templates:
            menu: 'easy_admin/menu.html.twig'
        assets:
            css:
                - 'admin/admin.css'
