easy_admin:
    design:
        menu:
            - { entity: 'Actualite', label: 'Actualités' }
            - { entity: 'Photo', label: 'Photos' }
            - { entity: 'Evenement', label: 'Evenements'}
            - { entity: 'User', label: 'Utilisateurs' }
            - { entity: 'ContenuStatic', label: 'Contenus Statiques'}
            - { entity: 'Activite', label: 'Activites'}
            - { entity: 'Categorie', label: 'Categories'}
