easy_admin:
    entities:
        Evenement:
            class: AppBundle\Entity\Evenement
            list:
                title: 'Liste des evenements'
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.evenement_images%' }
                    - date
                    - titre
                    - description
                    - inscrits
                    - photos
            show:
                title: "Détail de l'évènement"
                fields:
                    - date
                    - titre
                    - { property: 'image', type: 'image', base_path: '%app.path.evenement_images%' }
                    - description
                    - contenu
                    - inscrits
                    - { property: 'photos', template: 'easy_admin/Evenements/show_evenement.html.twig' }


            form:
                fields:
                    - date
                    - { property: 'imageFile', type: 'vich_image' }
                    - titre
                    - description
                    - weezeventLink
                    - contenu
                    - { property: 'inscrits', label: 'Inscrits', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\User', by_reference: true } }
                    - { property: 'photos', type: 'collection', type_options: { entry_type: 'AppBundle\Form\PhotoType', by_reference: false }}
