easy_admin:
    entities:
        Licence:
            class: AppBundle\Entity\Licence
            list:
                title: 'Liste des Licences'
                fields:
                    - numero
                    - nom
                    - prenom
                    - birthdate
                    - adresse
                    - codePostal
                    - Ville
                    - user
                    - activite
                    - saison
                    - categorieAge
