easy_admin:
    entities:
        User:
            controller: AppBundle\Controller\SecurityController
            class: AppBundle\Entity\User
            list:
                dql_filter: "entity.roles LIKE '%%env(ROLE_ADMIN)%%'"
                title: 'liste des utilisateurs'
                fields:
                    - { property: 'enabled', type: 'toggle', label: 'Actif'}
                    - 'nom'
                    - 'prenom'
                    - 'email'
                    - 'codePostal'
                    - 'ville'
                    - { property: 'birthdate', format: 'd/m/Y', label: 'date de naissance' }
                    - { property: 'admin', type: 'toggle'}
            form:
                title: 'Ajouter/Editer un utilisateur'
                fields:
                    - 'nom'
                    - 'prenom'
                    - 'email'
                    - 'adresse'
                    - 'codePostal'
                    - 'ville'
                    - { property: 'birthdate', format: 'd/m/Y', label: 'date de naissance', type_options: {'widget': 'single_text', 'format': 'dd/MM/yyyy' }}
                    - { property: 'plainPassword', type: 'password', label: 'mot de passe' }
            show:
                title: 'Visualiser un utilisateur'
                fields:
                    - { property: 'enabled', type: 'toggle', label: 'Actif'}
                    - 'nom'
                    - 'prenom'
                    - 'email'
                    - 'adresse'
                    - 'codePostal'
                    - 'ville'
                    - { property: 'birthdate', format: 'd/m/Y', label: 'date de naissance'}
                    - { property: 'admin', type: 'toggle'}

            new:
                title: 'Ajouter un utilisateur'

            edit:
                title: 'Modifier un utilisateur'

